name = "pontal-stock-frontend"
pages_build_output_dir = "out"
compatibility_date = "2024-01-01"

# Preview environment
[env.preview]
vars = { ENVIRONMENT = "preview" }

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

